[package]
name = "mysh"
version = "0.1.0"
authors = ["Randy SchÃ¼tt <rswhite4@googlemail.com>"]
edition = "2018"

[dependencies]
termion = "1.5.1"
whoami = "0.5.0"
toml = "0.5.0"
serde_derive = "1.0.90"
serde = "1.0.90"
